sonar.projectKey=ComicStore
sonar.projectName=ComicStore
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
# This property is optional if sonar.modules is set. 
sonar.sources=.
sonar.language=py

# Exclude directories that do not contain source code
sonar.exclusions=**/migrations/**, **/static/**, **/staticfiles/**, **/media/**, **/.venv/**, **/PruebaDesarrolloWeb3/**, db.sqlite3, manage.py, agregar_pais.py, cargar_*.py, comicstore/settings*.py, comicstore/asgi.py, comicstore/wsgi.py

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Configuration for test execution and coverage
# These will be useful once we configure unit testing
sonar.tests=.
sonar.test.inclusions=**/tests.py, **/tests/**, **/*_test.py
sonar.python.coverage.reportPaths=coverage.xml
