# Generated by Django 4.2.13 on 2026-04-02 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comic',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
